version: 'ci-build-{build}'

pull_requests:
  do_not_increment_build_number: true

image:
- Visual Studio 2017
- Ubuntu

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

configuration: Debug
build_script:
- pwsh: ./build.ps1 -Configuration $env:CONFIGURATION -BuildNumber $env:APPVEYOR_BUILD_NUMBER -CI
test_script:
- pwsh: ./test.ps1 -Configuration $env:CONFIGURATION

branches:
  except:
  - /^release\/.*$/

artifacts:
  - path: '**/*.nupkg'
    name: NuGet Packages

deploy:
  - provider: NuGet
    server: https://ci.appveyor.com/nuget/appcorenet-dependencyinjection
    api_key:
      secure: RFSWyPM/9cnKfMgh8YAG5IRYtKFAPW+Husl561qvxVA=
    on:
      branch: dev
